server:
  port: 9000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-port: 9000
    service-url:
      defaultZone: http://localhost:9000/eureka/
logging:
  level:
    root: info
