eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${config_server_addr}:9000/eureka/
  instance:
    hostname: ${config_server_addr}
