server:
  port: 10001

config_server_addr: localhost  

spring:
  application:
    name: CARDHOLDER-SERVICE
  zipkin:
    enabled: true
    base-url: http://${config_server_addr}:9411/
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.type: INFO
