server:
  port: 9002

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CARDHOLDER-SERVICE
          uri: lb://CARDHOLDER-SERVICE
          predicates:
            - Path=/cardholders/**
          filters:
            - name: CircuitBreaker
              args:
                name: CARDHOLDER-SERVICE
                fallbackuri: forward:/cardholderServiceFallback
        - id: CARD-SERVICE
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/cards/**
          filters:
            - name: CircuitBreaker
              args:
                name: CARD-SERVICE
                fallbackuri: forward:/cardServiceFallback
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallback


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
