server:
  port: 10003

spring:
  application:
    name: USER-SERVICE
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.type: TRACE
