server:
  port: 9001
spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/common-config
logging:
  level:
    root: info
config_server_addr: localhost
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${config_server_addr}:9000/eureka/
  instance:
    hostname: ${config_server_addr}
